[project]
name = "traffic-slice"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "geocoder>=1.38.1",
    "mitmproxy>=11.0.0",
    "pyperclip>=1.9.0",
]
